user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;

    keepalive_timeout  65;

    server {
      listen 0.0.0.0:80;
      charset utf-8;
      server_tokens off;
      access_log off;

      # Sendfile copies data between one FD and other from within the kernel.
      sendfile on;

      # Causes nginx to attempt to send its HTTP response head in one packet, instead of using partial frames.
      tcp_nopush on;

      # Don't buffer data-sends (disable Nagle algorithm).
      tcp_nodelay on;

      # Timeout for keep-alive connections. Server will close connections after this time.
      keepalive_timeout 65;

      # Allow the server to close the connection after a client stops responding.
      reset_timedout_connection on;

      # Defines a timeout for reading client request body. The timeout is set only for a period between two successive read operations, not for the transmission of the whole request body.
      client_body_timeout 30;

      root   /usr/share/nginx/html;

      gzip on;

      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_http_version 1.1;
      gzip_min_length 0;
      gzip_types text/plain application/javascript text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype;

      add_header X-Frame-Options "Deny";

      location / {
          try_files $uri$args $uri$args/ /index.html;
          location ~* .(html) {
              # security headers
              add_header X-XSS-Protection "1; mode=block";
              add_header X-Frame-Options "Deny";

              # See https://content-security-policy.com/ for details
              add_header Content-Security-Policy "default-src 'none'; manifest-src 'self'; script-src 'self' BOARD_URL_TO_REPLACE; style-src 'self' 'unsafe-inline' use.fontawesome.com cdnjs.cloudflare.com; img-src 'self' data: API_URL_TO_REPLACE; connect-src 'self' API_URL_TO_REPLACE BOARD_URL_TO_REPLACE; font-src 'self' use.fontawesome.com cdnjs.cloudflare.com fonts.gstatic.com;" always;
              # Do not cache index file.
              expires 0;
              add_header Cache-Control "public, no-cache";
          }
      }

      # JS and CSS files contain a hash in their names so we can cached them for a long time
      location ~* \.(js|css)$ {
          expires 1y;
          etag off;
          if_modified_since off;
          add_header Cache-Control "public, no-transform";
      }

      # cache image files for a hour
      location ~* \.(jpg|jpeg|png|gif|ico|svg)$ {
          expires 1h;
          add_header Cache-Control "public, no-transform";
      }

      # JSON files revalidation using a validation request with ETags
      location ~* \.(json)$ {
          add_header Cache-Control "public, no-cache";
      }

      # font files can also be cached for a long time
      location ~* \.(eot|otf|ttf|woff|woff2)$ {
          expires 1y;
          etag off;
          if_modified_since off;
          add_header Cache-Control "public, no-transform";
          add_header Access-Control-Allow-Origin *;
      }
    }
}
